name: Docker Registry (api)

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "docker/api.Dockerfile*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./api
          build-args: GIT_SHA=${{ github.sha }}
          file: ./docker/api.Dockerfile
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/it-is-me-api:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
